### ISSUE TITLE
Check configuration not visible in IcingaWeb2

### ISSUE THREAD

**Issue by K0nne** [Icinga/check_by_powershell#21]
Hello,

we configured a few checks via check_by_powershell according to the provided command.conf and example.conf.
They are working fine (great work btw 👍), but unfortunately it is not possible to see the check configuration in IcingaWeb2 anymore:

![21-01-_2021_14-04-34](https://user-images.githubusercontent.com/34264690/105355240-1bb51e80-5bf2-11eb-998c-575e0e6115c4.png)

Is it possible to fix this? Being able to see the check configuration is very helpful.

**Comment by lazyfrosch** [comment]
Not an issue of this project in particular, Icinga 2 can not export Functions to the IDO, their code is evaluated on check execution.

In our case, these vars are only used to build the commandline for `check_by_powershell`, all other customvars like `powershell_critical` should be visible here when set.

To see the command line executed by Icinga, one could use the Director Inspect feature.

Basically you should hide these vars in Icinga Web 2 via `protected_customvars`, see [monitoring Configuration](https://icinga.com/docs/icinga-web-2/latest/modules/monitoring/doc/03-Configuration/)
